framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Serializer\RabbitMQMessageSerializer
                options:
                    exchange:
                        name: rarecare_events
                        type: topic
                    queues:
                        dossier_medical_message:
                            binding_keys: ["get_d_m"]

        routing:
            App\Message\PatientCreate: async
