framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: patient_events
                        type: topic
                    queues:
                        patient_created_queue:
                        binding_keys: ["patient.created"]

        routing:
            App\Message\PatientCreate: async
