server {
    listen 80;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;

    resolver 127.0.0.11 valid=30s;

    # Gateway Routing
    location /api/patients/ {
        set $upstream_patients patients;
        proxy_pass http://$upstream_patients:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/maladie/ {
        set $upstream_maladie maladie;
        proxy_pass http://$upstream_maladie:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/traitement/ {
        set $upstream_traitement traitement;
        proxy_pass http://$upstream_traitement:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/medical-dossier/ {
        set $upstream_medical_dossier medical-dossier;
        proxy_pass http://$upstream_medical_dossier:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/authentification/ {
        set $upstream_auth authentification;
        proxy_pass http://$upstream_auth:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/autorisation/ {
        set $upstream_auto autorisation;
        proxy_pass http://$upstream_auto:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
