FROM php:8.4-cli

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libzip-dev \
    librabbitmq-dev \
    zip \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql zip opcache \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install amqp \
&& docker-php-ext-enable amqp
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www/html

EXPOSE 8000

CMD php -S 0.0.0.0:8000 public/index.php
